# Book settings
title: COSC 122
author: Firas Moosvi
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md","files/*"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  baseurl : "https://firas.moosvi.com/courses/2022_WT2/cosc122"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  google_analytics_id: UA-168693744-4 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "ubco-cmps/cosc122_course"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

repository: 
  url          : https://github.com/ubco-cmps/cosc122_course
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - substitution
    myst_substitutions:
      INSTRUCTOR: "Dr. Firas Moosvi (he/his/him)"
      PRONOUNCE: "[Fur-az Moose-vee](https://namedrop.io/firasmoosvi)"
      OFFICE: "SCI 393"
      PHONE: "N/A"
      COURSE_CODE: "COSC 122"
      SECTION: "001"
      CREDITS: "3"
      TITLE: "Computer Fluency"
      PREREQS: "None."
      COREQS: "None."
      TERM: "2022 Winter Term 2"
      ROOM: "COM 201"
      MEETING_TIMES: "Wednesday, Friday from 14:00 - 15:30 PM"
      GRACE_PERIOD: "48 hour"
      W_DATE_1: "11:59 PDT on September 19, 2022"
      W_DATE_2: "11:59 PDT on November 18, 2022"
      W_DATE_3: "November 18, 2022"
      EXAM_PERIOD: "Sunday Dec 11th - Thursday, Dec 22"
      CANVAS_ID: "100274"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID" # {{ '[course website]({link})'.format(link=CANVAS_LINK.replace('CANVAS_ID',CANVAS_ID)) }}
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      LAB_SCHEDULE_HERE: "[Lab Schedule here](https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-course&dept=COSC&course=122)"
      ANNOUNCEMENTS_LINK: "[Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/2022_WT2/cosc122"
      FORUM_LINK: "[Ed Discussion](https://edstem.org/us/courses/XX/discussion/XX)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410)"
      FORMAT: "Lectures will be held in-person and will be recorded (if technology permits)."
      ASSOCIATE_HEAD: "Yves Lucet [yves.lucet@ubc.ca](mailto:yves.lucet@ubc.ca)"
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/jfe/form/XXX)"
